# Generated by Django 4.0.5 on 2022-06-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumos',
            new_name='Alumnos',
        ),
    ]
